services:
  db-belajar:
    image: postgres
    environment:
      - POSTGRES_DB=belajar-authentication
      - POSTGRES_USER=belajar
      - POSTGRES_PASSWORD=authentication
    ports:
      - 5432:5432
    volumes:
      - ./db-belajar:/var/lib/postgresql/data